version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      npm-all:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directories:
      - "/packages/*"
    schedule:
      interval: "weekly"
    groups:
      docker-all:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions-all:
        patterns:
          - "*"
