receivers:
  # Collect host metrics
  hostmetrics:
    collection_interval: 30s
    root_path: /hostfs
    scrapers:
      cpu: {}
      load: {}
      memory: {}
      disk: {}
      filesystem: {}
      network: {}

  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  # Scrape Prometheus metrics from Docker containers
  prometheus:
    config:
      global:
        scrape_interval: 60s
      scrape_configs:
        # Agent's own metrics
        - job_name: otel-collector-agent
          static_configs:
            - targets:
                - localhost:8888

processors:
  # Minimal processing for agents
  resourcedetection:
    detectors:
      - env
      - system
    timeout: 2s

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

exporters:
  debug:
    verbosity: detailed

service:
  telemetry:
    logs:
      encoding: json
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: 0.0.0.0
                port: 8888
  extensions:
    - health_check

  pipelines:
    metrics/otlp:
      receivers: [otlp]
      processors: [resourcedetection]
      exporters: [debug]
