version: "3"

services:
  prometheus:
    image: prom/prometheus:v2.49.1
    container_name: prometheus
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${PROM_DATA_DIR}/prometheus_data:/prometheus
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--enable-feature=agent'
    networks:
      - metrics

networks:
  metrics:
    external: true
    name: metrics
