version: "3"

services:
  loki:
    image: grafana/loki:2.9.4
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml
    # volumes:
    #   - ./config/loki.yaml:/etc/loki/local-config.yaml
    expose:
      - "3100"
    networks:
      - metrics

  prometheus:
    image: prom/prometheus:v2.45.3
    restart: unless-stopped
    user: "${UID}:${GID}"
    expose:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${PROM_DATA_DIR}/prometheus_data:/prometheus
    networks:
      - web
      - metrics
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=60d"
      - "--web.enable-lifecycle"

  grafana:
    image: grafana/grafana:10.3.1
    restart: unless-stopped
    user: "${UID}:${GID}"
    depends_on:
      - loki
    expose:
      - "3000:3000"
    volumes:
      - ${PROM_DATA_DIR}/grafana_data:/var/lib/grafana
    networks:
      - web
      - metrics
    labels:
      - "traefik.docker.network=sushii-2_web"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.routers.grafana.rule=Host(`grafana.sushii.xyz`)"
      - "traefik.http.routers.grafana.entrypoints=secure"
      - "traefik.http.routers.grafana.tls.certresolver=acme"

networks:
  web:
    external: true
    name: sushii-2_web
  metrics:
    name: metrics
