server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080

clients:
  - url: http://${LOKI_URL}/loki/api/v1/push
    tls_config:
      # Tailscale not through traefik rn
      insecure_skip_verify: true

scrape_configs:
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          __path__: /var/lib/docker/containers/*/*-json.log

    pipeline_stages:
      - json:
          expressions:
            log:
            timestamp: time
            service_name: attrs.service_name
      - json:
          expressions:
            level: level
            mod: mod
            hostname: hostname
            msg: msg
          source: log
      - labels:
          app: service_name
          level:
          mod:
          hostname:
      - match:
          selector: '{app=""}'
          action: drop
      - labeldrop:
          - filename
          - attrs
          - attrs_production_status
          - attrs_service_name
          - stream
          - msg
          - log
      - labelallow:
          - app
          - env
          - hostname
          - job
          - level
          - mod
          - time
      - output:
          source: log
