name: Build and Push API Proxy Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag (leave empty for SHA)'
        required: false
        default: ''

jobs:
  docker-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get short SHA
        id: sha
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set image tag
        id: tag
        run: |
          if [ -n "${{ github.event.inputs.tag }}" ]; then
            echo "image_tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          else
            echo "image_tag=${{ steps.sha.outputs.sha_short }}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: ./packages/api-proxy
          file: ./packages/api-proxy/Dockerfile
          tags: |
            ghcr.io/sushiibot/api-proxy:latest
            ghcr.io/sushiibot/api-proxy:${{ steps.tag.outputs.image_tag }}
          cache-from: type=registry,ref=ghcr.io/sushiibot/api-proxy:buildcache
          cache-to: type=registry,ref=ghcr.io/sushiibot/api-proxy:buildcache,mode=max

      - name: Output image info
        run: |
          echo "Built and pushed image: ghcr.io/sushiibot/api-proxy:${{ steps.tag.outputs.image_tag }}"
          echo "Also tagged as: ghcr.io/sushiibot/api-proxy:latest"