name: CI

on:
  push:
    paths-ignore:
      - "docs/**"
  pull_request:
    branches: [main]
    paths-ignore:
      - "docs/**"

jobs:
  test:
    name: Test sushii-worker
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17.5-bookworm
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install sushii-worker dependencies
        run: bun install --immutable

      - name: Typecheck sushii-worker
        run: cd packages/sushii-worker && bun run typecheck

      - name: Initialize database roles
        run: |
          PGPASSWORD=postgres psql -h localhost -U postgres -d postgres -f packages/sushii-worker/drizzle/init.sql

      - name: Run drizzle database migrations
        working-directory: ./packages/sushii-worker
        run: |
          cp .env.ci .env
          bun run drizzle-kit migrate

      - name: Test sushii-worker
        run: |
          cp ./packages/sushii-worker/.env.ci ./packages/sushii-worker/.env
          cd ./packages/sushii-worker
          bun test

  docker-build:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.sha.outputs.sha_short }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get short SHA
        id: sha
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: .
          file: ./packages/sushii-worker/Dockerfile
          build-args: |
            GIT_HASH=${{ steps.sha.outputs.sha_short }}
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
          tags: |
            ghcr.io/sushiibot/sushii-worker:latest
            ghcr.io/sushiibot/sushii-worker:${{ steps.sha.outputs.sha_short }}
          cache-from: type=registry,ref=ghcr.io/sushiibot/sushii-worker:buildcache
          cache-to: type=registry,ref=ghcr.io/sushiibot/sushii-worker:buildcache,mode=max

  deploy-staging:
    needs: docker-build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout deployment playbook
        uses: actions/checkout@v4
        with:
          repository: sushiibot/sushii-ansible
          ref: main
          token: ${{ secrets.ANSIBLE_REPO_TOKEN }}

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup known host
        run: |
          mkdir -p ~/.ssh
          echo "$KNOWN_HOST" > ~/.ssh/known_hosts
        env:
          KNOWN_HOST: ${{ secrets.KNOWN_HOST }}

      - name: Deploy to staging
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        run: |

          # Remove unused vault file
          rm ./inventory/group_vars/all/vault.yml

          ansible-playbook \
            --vault-password-file ./vault-env \
            -l apps \
            playbooks/deploy.yml \
            -e "service=sushii-bot/sushii-bot-staging" \
            -e "image_version=${{ needs.docker-build.outputs.sha_short }}" \
            -e "docker_registry_password=${{ secrets.GITHUB_TOKEN }}" \
            -e "docker_registry_user=${{ github.repository_owner }}" \
            -t deploy
