name: Docs

on:
  push:
    paths:
      - "docs/**"
  pull_request:
    branches: [main]
    paths:
      - "docs/**"

jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install sushii-worker dependencies
        run: bun install --immutable
        working-directory: ./docs

      - name: Test sushii-worker
        run: bun run build
        working-directory: ./docs

      - uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./docs/dist/

  deploy:
    name: Deploy Docs
    needs: build
    permissions:
      # to deploy to Pages
      pages: write
      # to verify the deployment originates from an appropriate source
      id-token: write

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
