name: Docs

on:
  push:
    paths:
      - "docs/**"
  pull_request:
    branches: [main]
    paths:
      - "docs/**"

jobs:
  build_docs:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install sushii-worker dependencies
        run: bun install --immutable
        working-directory: ./docs

      - name: Test sushii-worker
        run: bun build
        working-directory: ./docs
